name: Deploy FastAPI Via CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no adetunmbikenny@34.46.128.75 '
            cd /home/adetunmbikenny/fastapi-book-project-1 &&
            git pull &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart nginx &&
            sudo systemctl restart fastapi
          '